export const enum UserTypes {
    LOGIN_USER = 'LOGIN_USER',
    SIGNUP_USER = 'SIGNUP_USER',
    SET_USER = 'SET_USER',
    SET_NEW_AVATAR = 'SET_NEW_AVATAR',
    SET_GAMES_HISTORY = 'SET_GAMES_HISTORY',
    SET_USER_AUTHORIZED = 'SET_USER_AUTHORIZED',
    RESET_USER_AUTHORIZED = 'RESET_USER_AUTHORIZED',
    SET_ERROR = 'SET_ERROR',
    RESET_ERROR = 'RESET_ERROR',
    SET_LOADING = 'SET_LOADING'
}
